added customNamespace
logzio/cloudwatch-metrics-helpers pull request #14
Opened 2024-01-24 10:09 UTC by bardabun

This pull request introduces the `CUSTOM_NAMESPACE` parameter to enhance the CloudWatch Metrics Stream integration. It allows users to define a unique namespace for their CloudWatch metrics, providing greater flexibility and categorization for custom metrics monitoring. This update complements the existing `AWS_NAMESPACES` functionality.

2024-01-24 10:32 UTC, mirii1994 requested changes
Amazing!
Please see my comment :)

2024-01-24 10:32 UTC, mirii1994 commented on namespaces/main.go
> +		if fullNsStr != emptyString {
I'm not a fan of how this condition looks... it's not straight forward in my opinion
Please change it to be more readable :)

2024-01-24 12:18 UTC, mirii1994 approved these changes
Great!

2024-01-29 10:47 UTC, nico-shishkin approved these changes

2024-01-30 09:13 UTC, merged